name: resizer_backend

services:
  fastapi:
    container_name: fastapi_resizer_backend
    hostname: fastapi
    environment:
      - DEBUG=True
      - SERVER_PORT=8000
    image: resizer_fastapi_dev
    build:
      target: dev
    restart: unless-stopped
    volumes:
      - ./:/resizer
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"


