name: resizer_backend

services:
  fastapi:
    container_name: fastapi_resizer_backend
    hostname: fastapi
    env_file:
      - .env
    image: resizer_fastapi_dev
    build:
      target: dev
    restart: unless-stopped
    volumes:
      - ./:/resizer
    command: uvicorn src.app:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"


